//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace Infrastructure.DAL
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Department))]
    public partial class Carrer: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int id
        {
            get { return _id; }
            set
            {
                if (_id != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'id' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _id = value;
                    OnPropertyChanged("id");
                }
            }
        }
        private int _id;
    
        [DataMember]
        public string EnContent
        {
            get { return _enContent; }
            set
            {
                if (_enContent != value)
                {
                    _enContent = value;
                    OnPropertyChanged("EnContent");
                }
            }
        }
        private string _enContent;
    
        [DataMember]
        public string ArContent
        {
            get { return _arContent; }
            set
            {
                if (_arContent != value)
                {
                    _arContent = value;
                    OnPropertyChanged("ArContent");
                }
            }
        }
        private string _arContent;
    
        [DataMember]
        public Nullable<System.DateTime> StartDate
        {
            get { return _startDate; }
            set
            {
                if (_startDate != value)
                {
                    _startDate = value;
                    OnPropertyChanged("StartDate");
                }
            }
        }
        private Nullable<System.DateTime> _startDate;
    
        [DataMember]
        public Nullable<System.DateTime> EndDate
        {
            get { return _endDate; }
            set
            {
                if (_endDate != value)
                {
                    _endDate = value;
                    OnPropertyChanged("EndDate");
                }
            }
        }
        private Nullable<System.DateTime> _endDate;
    
        [DataMember]
        public Nullable<bool> IsPublished
        {
            get { return _isPublished; }
            set
            {
                if (_isPublished != value)
                {
                    _isPublished = value;
                    OnPropertyChanged("IsPublished");
                }
            }
        }
        private Nullable<bool> _isPublished;
    
        [DataMember]
        public string Author
        {
            get { return _author; }
            set
            {
                if (_author != value)
                {
                    _author = value;
                    OnPropertyChanged("Author");
                }
            }
        }
        private string _author;
    
        [DataMember]
        public Nullable<bool> Status
        {
            get { return _status; }
            set
            {
                if (_status != value)
                {
                    _status = value;
                    OnPropertyChanged("Status");
                }
            }
        }
        private Nullable<bool> _status;
    
        [DataMember]
        public string ArTitle
        {
            get { return _arTitle; }
            set
            {
                if (_arTitle != value)
                {
                    _arTitle = value;
                    OnPropertyChanged("ArTitle");
                }
            }
        }
        private string _arTitle;
    
        [DataMember]
        public string EnTitle
        {
            get { return _enTitle; }
            set
            {
                if (_enTitle != value)
                {
                    _enTitle = value;
                    OnPropertyChanged("EnTitle");
                }
            }
        }
        private string _enTitle;
    
        [DataMember]
        public Nullable<int> DeptID
        {
            get { return _deptID; }
            set
            {
                if (_deptID != value)
                {
                    ChangeTracker.RecordOriginalValue("DeptID", _deptID);
                    if (!IsDeserializing)
                    {
                        if (Department != null && Department.ID != value)
                        {
                            Department = null;
                        }
                    }
                    _deptID = value;
                    OnPropertyChanged("DeptID");
                }
            }
        }
        private Nullable<int> _deptID;
    
        [DataMember]
        public string EnFName
        {
            get { return _enFName; }
            set
            {
                if (_enFName != value)
                {
                    _enFName = value;
                    OnPropertyChanged("EnFName");
                }
            }
        }
        private string _enFName;
    
        [DataMember]
        public string ArFName
        {
            get { return _arFName; }
            set
            {
                if (_arFName != value)
                {
                    _arFName = value;
                    OnPropertyChanged("ArFName");
                }
            }
        }
        private string _arFName;
    
        [DataMember]
        public string EnLName
        {
            get { return _enLName; }
            set
            {
                if (_enLName != value)
                {
                    _enLName = value;
                    OnPropertyChanged("EnLName");
                }
            }
        }
        private string _enLName;
    
        [DataMember]
        public string ArLName
        {
            get { return _arLName; }
            set
            {
                if (_arLName != value)
                {
                    _arLName = value;
                    OnPropertyChanged("ArLName");
                }
            }
        }
        private string _arLName;
    
        [DataMember]
        public string Email
        {
            get { return _email; }
            set
            {
                if (_email != value)
                {
                    _email = value;
                    OnPropertyChanged("Email");
                }
            }
        }
        private string _email;
    
        [DataMember]
        public string EnGender
        {
            get { return _enGender; }
            set
            {
                if (_enGender != value)
                {
                    _enGender = value;
                    OnPropertyChanged("EnGender");
                }
            }
        }
        private string _enGender;
    
        [DataMember]
        public string ArGender
        {
            get { return _arGender; }
            set
            {
                if (_arGender != value)
                {
                    _arGender = value;
                    OnPropertyChanged("ArGender");
                }
            }
        }
        private string _arGender;
    
        [DataMember]
        public string EnCountry
        {
            get { return _enCountry; }
            set
            {
                if (_enCountry != value)
                {
                    _enCountry = value;
                    OnPropertyChanged("EnCountry");
                }
            }
        }
        private string _enCountry;
    
        [DataMember]
        public string ArCountry
        {
            get { return _arCountry; }
            set
            {
                if (_arCountry != value)
                {
                    _arCountry = value;
                    OnPropertyChanged("ArCountry");
                }
            }
        }
        private string _arCountry;
    
        [DataMember]
        public string Encity
        {
            get { return _encity; }
            set
            {
                if (_encity != value)
                {
                    _encity = value;
                    OnPropertyChanged("Encity");
                }
            }
        }
        private string _encity;
    
        [DataMember]
        public string ArCity
        {
            get { return _arCity; }
            set
            {
                if (_arCity != value)
                {
                    _arCity = value;
                    OnPropertyChanged("ArCity");
                }
            }
        }
        private string _arCity;
    
        [DataMember]
        public string EnAddress
        {
            get { return _enAddress; }
            set
            {
                if (_enAddress != value)
                {
                    _enAddress = value;
                    OnPropertyChanged("EnAddress");
                }
            }
        }
        private string _enAddress;
    
        [DataMember]
        public string ArAddress
        {
            get { return _arAddress; }
            set
            {
                if (_arAddress != value)
                {
                    _arAddress = value;
                    OnPropertyChanged("ArAddress");
                }
            }
        }
        private string _arAddress;
    
        [DataMember]
        public string Telephone
        {
            get { return _telephone; }
            set
            {
                if (_telephone != value)
                {
                    _telephone = value;
                    OnPropertyChanged("Telephone");
                }
            }
        }
        private string _telephone;
    
        [DataMember]
        public string Mobile
        {
            get { return _mobile; }
            set
            {
                if (_mobile != value)
                {
                    _mobile = value;
                    OnPropertyChanged("Mobile");
                }
            }
        }
        private string _mobile;
    
        [DataMember]
        public string EnNationality
        {
            get { return _enNationality; }
            set
            {
                if (_enNationality != value)
                {
                    _enNationality = value;
                    OnPropertyChanged("EnNationality");
                }
            }
        }
        private string _enNationality;
    
        [DataMember]
        public string ArNationality
        {
            get { return _arNationality; }
            set
            {
                if (_arNationality != value)
                {
                    _arNationality = value;
                    OnPropertyChanged("ArNationality");
                }
            }
        }
        private string _arNationality;
    
        [DataMember]
        public string EnMaritalStatus
        {
            get { return _enMaritalStatus; }
            set
            {
                if (_enMaritalStatus != value)
                {
                    _enMaritalStatus = value;
                    OnPropertyChanged("EnMaritalStatus");
                }
            }
        }
        private string _enMaritalStatus;
    
        [DataMember]
        public string ArMaritalStatus
        {
            get { return _arMaritalStatus; }
            set
            {
                if (_arMaritalStatus != value)
                {
                    _arMaritalStatus = value;
                    OnPropertyChanged("ArMaritalStatus");
                }
            }
        }
        private string _arMaritalStatus;
    
        [DataMember]
        public string EnMilitaryStatus
        {
            get { return _enMilitaryStatus; }
            set
            {
                if (_enMilitaryStatus != value)
                {
                    _enMilitaryStatus = value;
                    OnPropertyChanged("EnMilitaryStatus");
                }
            }
        }
        private string _enMilitaryStatus;
    
        [DataMember]
        public string ArMilitaryStatus
        {
            get { return _arMilitaryStatus; }
            set
            {
                if (_arMilitaryStatus != value)
                {
                    _arMilitaryStatus = value;
                    OnPropertyChanged("ArMilitaryStatus");
                }
            }
        }
        private string _arMilitaryStatus;
    
        [DataMember]
        public Nullable<bool> IsHaveDriveLicense
        {
            get { return _isHaveDriveLicense; }
            set
            {
                if (_isHaveDriveLicense != value)
                {
                    _isHaveDriveLicense = value;
                    OnPropertyChanged("IsHaveDriveLicense");
                }
            }
        }
        private Nullable<bool> _isHaveDriveLicense;
    
        [DataMember]
        public Nullable<bool> IsHaveCar
        {
            get { return _isHaveCar; }
            set
            {
                if (_isHaveCar != value)
                {
                    _isHaveCar = value;
                    OnPropertyChanged("IsHaveCar");
                }
            }
        }
        private Nullable<bool> _isHaveCar;
    
        [DataMember]
        public string EnCareerObjective
        {
            get { return _enCareerObjective; }
            set
            {
                if (_enCareerObjective != value)
                {
                    _enCareerObjective = value;
                    OnPropertyChanged("EnCareerObjective");
                }
            }
        }
        private string _enCareerObjective;
    
        [DataMember]
        public string ArCareerObjective
        {
            get { return _arCareerObjective; }
            set
            {
                if (_arCareerObjective != value)
                {
                    _arCareerObjective = value;
                    OnPropertyChanged("ArCareerObjective");
                }
            }
        }
        private string _arCareerObjective;
    
        [DataMember]
        public string EnHighSchool
        {
            get { return _enHighSchool; }
            set
            {
                if (_enHighSchool != value)
                {
                    _enHighSchool = value;
                    OnPropertyChanged("EnHighSchool");
                }
            }
        }
        private string _enHighSchool;
    
        [DataMember]
        public string ArHighSchool
        {
            get { return _arHighSchool; }
            set
            {
                if (_arHighSchool != value)
                {
                    _arHighSchool = value;
                    OnPropertyChanged("ArHighSchool");
                }
            }
        }
        private string _arHighSchool;
    
        [DataMember]
        public string EnUniversity
        {
            get { return _enUniversity; }
            set
            {
                if (_enUniversity != value)
                {
                    _enUniversity = value;
                    OnPropertyChanged("EnUniversity");
                }
            }
        }
        private string _enUniversity;
    
        [DataMember]
        public string ArUniversity
        {
            get { return _arUniversity; }
            set
            {
                if (_arUniversity != value)
                {
                    _arUniversity = value;
                    OnPropertyChanged("ArUniversity");
                }
            }
        }
        private string _arUniversity;
    
        [DataMember]
        public string GraduateYear
        {
            get { return _graduateYear; }
            set
            {
                if (_graduateYear != value)
                {
                    _graduateYear = value;
                    OnPropertyChanged("GraduateYear");
                }
            }
        }
        private string _graduateYear;
    
        [DataMember]
        public string EnCources
        {
            get { return _enCources; }
            set
            {
                if (_enCources != value)
                {
                    _enCources = value;
                    OnPropertyChanged("EnCources");
                }
            }
        }
        private string _enCources;
    
        [DataMember]
        public string ArCources
        {
            get { return _arCources; }
            set
            {
                if (_arCources != value)
                {
                    _arCources = value;
                    OnPropertyChanged("ArCources");
                }
            }
        }
        private string _arCources;
    
        [DataMember]
        public string EnWorkExperince
        {
            get { return _enWorkExperince; }
            set
            {
                if (_enWorkExperince != value)
                {
                    _enWorkExperince = value;
                    OnPropertyChanged("EnWorkExperince");
                }
            }
        }
        private string _enWorkExperince;
    
        [DataMember]
        public string ArWorkExperince
        {
            get { return _arWorkExperince; }
            set
            {
                if (_arWorkExperince != value)
                {
                    _arWorkExperince = value;
                    OnPropertyChanged("ArWorkExperince");
                }
            }
        }
        private string _arWorkExperince;
    
        [DataMember]
        public string EnHobbies
        {
            get { return _enHobbies; }
            set
            {
                if (_enHobbies != value)
                {
                    _enHobbies = value;
                    OnPropertyChanged("EnHobbies");
                }
            }
        }
        private string _enHobbies;
    
        [DataMember]
        public string ArHobbies
        {
            get { return _arHobbies; }
            set
            {
                if (_arHobbies != value)
                {
                    _arHobbies = value;
                    OnPropertyChanged("ArHobbies");
                }
            }
        }
        private string _arHobbies;
    
        [DataMember]
        public string ComputerSkills
        {
            get { return _computerSkills; }
            set
            {
                if (_computerSkills != value)
                {
                    _computerSkills = value;
                    OnPropertyChanged("ComputerSkills");
                }
            }
        }
        private string _computerSkills;
    
        [DataMember]
        public string EnLanguages
        {
            get { return _enLanguages; }
            set
            {
                if (_enLanguages != value)
                {
                    _enLanguages = value;
                    OnPropertyChanged("EnLanguages");
                }
            }
        }
        private string _enLanguages;
    
        [DataMember]
        public string ArLanguages
        {
            get { return _arLanguages; }
            set
            {
                if (_arLanguages != value)
                {
                    _arLanguages = value;
                    OnPropertyChanged("ArLanguages");
                }
            }
        }
        private string _arLanguages;

        #endregion
        #region Navigation Properties
    
        [DataMember]
        public Department Department
        {
            get { return _department; }
            set
            {
                if (!ReferenceEquals(_department, value))
                {
                    var previousValue = _department;
                    _department = value;
                    FixupDepartment(previousValue);
                    OnNavigationPropertyChanged("Department");
                }
            }
        }
        private Department _department;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            Department = null;
        }

        #endregion
        #region Association Fixup
    
        private void FixupDepartment(Department previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.Carrers.Contains(this))
            {
                previousValue.Carrers.Remove(this);
            }
    
            if (Department != null)
            {
                if (!Department.Carrers.Contains(this))
                {
                    Department.Carrers.Add(this);
                }
    
                DeptID = Department.ID;
            }
            else if (!skipKeys)
            {
                DeptID = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Department")
                    && (ChangeTracker.OriginalValues["Department"] == Department))
                {
                    ChangeTracker.OriginalValues.Remove("Department");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Department", previousValue);
                }
                if (Department != null && !Department.ChangeTracker.ChangeTrackingEnabled)
                {
                    Department.StartTracking();
                }
            }
        }

        #endregion
    }
}
