//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class menu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal menu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.menu", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Users List.
        /// </summary>
        internal static string AccessUsersList {
            get {
                return ResourceManager.GetString("AccessUsersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Analysis.
        /// </summary>
        internal static string AgentAnalysis {
            get {
                return ResourceManager.GetString("AgentAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget Panel.
        /// </summary>
        internal static string BudgetPanel {
            get {
                return ResourceManager.GetString("BudgetPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container Analysis.
        /// </summary>
        internal static string ContainerAnalysis {
            get {
                return ResourceManager.GetString("ContainerAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container Terminal.
        /// </summary>
        internal static string ContainerTerminal {
            get {
                return ResourceManager.GetString("ContainerTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analytics.
        /// </summary>
        internal static string CTAnalytics {
            get {
                return ResourceManager.GetString("CTAnalytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustodyDetails.
        /// </summary>
        internal static string CustodyDetails {
            get {
                return ResourceManager.GetString("CustodyDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customized Revenue Panel.
        /// </summary>
        internal static string CustomizedRevenuePanel {
            get {
                return ResourceManager.GetString("CustomizedRevenuePanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Revenue Panel.
        /// </summary>
        internal static string DailyRevenuePanel {
            get {
                return ResourceManager.GetString("DailyRevenuePanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Analytics.
        /// </summary>
        internal static string ExportAnalytics {
            get {
                return ResourceManager.GetString("ExportAnalytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GDB.
        /// </summary>
        internal static string GDB {
            get {
                return ResourceManager.GetString("GDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GDB Analytics.
        /// </summary>
        internal static string GDBAnalytics {
            get {
                return ResourceManager.GetString("GDBAnalytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Analytics.
        /// </summary>
        internal static string ImportAnalytics {
            get {
                return ResourceManager.GetString("ImportAnalytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KPI.
        /// </summary>
        internal static string KPI {
            get {
                return ResourceManager.GetString("KPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KPI Analytics.
        /// </summary>
        internal static string KPIAnalytics {
            get {
                return ResourceManager.GetString("KPIAnalytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules List.
        /// </summary>
        internal static string ModulesList {
            get {
                return ResourceManager.GetString("ModulesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Revenue Panel.
        /// </summary>
        internal static string MonthlyRevenuePanel {
            get {
                return ResourceManager.GetString("MonthlyRevenuePanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Volume Panel.
        /// </summary>
        internal static string MonthlyVolumePanel {
            get {
                return ResourceManager.GetString("MonthlyVolumePanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal Access.
        /// </summary>
        internal static string PortalAccess {
            get {
                return ResourceManager.GetString("PortalAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrintGateOut.
        /// </summary>
        internal static string PrintGateOut {
            get {
                return ResourceManager.GetString("PrintGateOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PurchaseItems.
        /// </summary>
        internal static string PurchaseItems {
            get {
                return ResourceManager.GetString("PurchaseItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Time - KPI.
        /// </summary>
        internal static string RT {
            get {
                return ResourceManager.GetString("RT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal Summery.
        /// </summary>
        internal static string TerminalSummery {
            get {
                return ResourceManager.GetString("TerminalSummery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        internal static string UserManagement {
            get {
                return ResourceManager.GetString("UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user Permission.
        /// </summary>
        internal static string userPermission {
            get {
                return ResourceManager.GetString("userPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vessels Analysis.
        /// </summary>
        internal static string VesselsAnalysis {
            get {
                return ResourceManager.GetString("VesselsAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yard Capacity.
        /// </summary>
        internal static string YardCapacity {
            get {
                return ResourceManager.GetString("YardCapacity", resourceCulture);
            }
        }
    }
}
