//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Utilities {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Utilities() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Utilities", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left.
        /// </summary>
        internal static string align {
            get {
                return ResourceManager.GetString("align", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALL.
        /// </summary>
        internal static string ALL {
            get {
                return ResourceManager.GetString("ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ar_bootstrap {
            get {
                return ResourceManager.GetString("ar_bootstrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Layout/.
        /// </summary>
        internal static string Assetspath {
            get {
                return ResourceManager.GetString("Assetspath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        internal static string cuture {
            get {
                return ResourceManager.GetString("cuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /ar-KW.
        /// </summary>
        internal static string cutureRoute {
            get {
                return ResourceManager.GetString("cutureRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ltr.
        /// </summary>
        internal static string dir {
            get {
                return ResourceManager.GetString("dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Found.
        /// </summary>
        internal static string foundTotal {
            get {
                return ResourceManager.GetString("foundTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Found.
        /// </summary>
        internal static string foundTotal1 {
            get {
                return ResourceManager.GetString("foundTotal1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullnameEn.
        /// </summary>
        internal static string Fullname {
            get {
                return ResourceManager.GetString("Fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ar-KW.
        /// </summary>
        internal static string langrouter {
            get {
                return ResourceManager.GetString("langrouter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ar/orange-grey.css.
        /// </summary>
        internal static string mainstyle {
            get {
                return ResourceManager.GetString("mainstyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NameEn.
        /// </summary>
        internal static string NameEn {
            get {
                return ResourceManager.GetString("NameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to navbar-left.
        /// </summary>
        internal static string navbarleft {
            get {
                return ResourceManager.GetString("navbarleft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records.
        /// </summary>
        internal static string records {
            get {
                return ResourceManager.GetString("records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record.
        /// </summary>
        internal static string records1 {
            get {
                return ResourceManager.GetString("records1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Layout/.
        /// </summary>
        internal static string resourcespath {
            get {
                return ResourceManager.GetString("resourcespath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to right.
        /// </summary>
        internal static string reversealign {
            get {
                return ResourceManager.GetString("reversealign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rtl.
        /// </summary>
        internal static string reversedir {
            get {
                return ResourceManager.GetString("reversedir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /UIResouces/scripts/.
        /// </summary>
        internal static string ribbonjspath {
            get {
                return ResourceManager.GetString("ribbonjspath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to right-sidebar.
        /// </summary>
        internal static string rightsidebar {
            get {
                return ResourceManager.GetString("rightsidebar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string selectLang {
            get {
                return ResourceManager.GetString("selectLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Layout/LTR/assets/images/flags/gb.png.
        /// </summary>
        internal static string SelectLangflag {
            get {
                return ResourceManager.GetString("SelectLangflag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /UIResouces/SideMenu/js/.
        /// </summary>
        internal static string sidemenustyle {
            get {
                return ResourceManager.GetString("sidemenustyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /UIResouces/styles/.
        /// </summary>
        internal static string stylepath {
            get {
                return ResourceManager.GetString("stylepath", resourceCulture);
            }
        }
    }
}
