//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.DAL.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetsItemUnits
    {
        public int Code { get; set; }
        public Nullable<int> InboundCode { get; set; }
        public Nullable<int> ItemCode { get; set; }
        public string UnitRefCode { get; set; }
        public string ItemTag { get; set; }
        public Nullable<double> Qty { get; set; }
        public Nullable<double> ReceivedQty { get; set; }
        public Nullable<int> QUnitCode { get; set; }
        public Nullable<double> EstimatedUnitCost { get; set; }
        public Nullable<int> UnitStatus { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<int> LastEventTrackingId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedAt { get; set; }
    
        public virtual D_ItemUsedStatus D_ItemUsedStatus { get; set; }
        public virtual D_ItemCard D_ItemCard { get; set; }
        public virtual D_QtyUnit D_QtyUnit { get; set; }
        public virtual Inbound Inbound { get; set; }
    }
}
