//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.DAL.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetsEventTracking
    {
        public int Code { get; set; }
        public Nullable<int> RequestHeaderCode { get; set; }
        public Nullable<int> AssetCode { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> actionId { get; set; }
        public Nullable<int> statusId { get; set; }
        public Nullable<int> ToLocationId { get; set; }
        public Nullable<int> EmpRefCode { get; set; }
        public string EmpName { get; set; }
        public string Notes { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedAt { get; set; }
        public Nullable<double> Qty { get; set; }
        public Nullable<double> MissedQty { get; set; }
        public string StoreRequestRefCode { get; set; }
        public Nullable<double> RequestItemPrice { get; set; }
    
        public virtual AssetsAvailabilityStatus AssetsAvailabilityStatus { get; set; }
        public virtual AssetsEventTrackingHeader AssetsEventTrackingHeader { get; set; }
        public virtual AssetsTrackingActions AssetsTrackingActions { get; set; }
        public virtual D_ItemCard D_ItemCard { get; set; }
    }
}
