//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.DAL.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetsEventTrackingHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssetsEventTrackingHeader()
        {
            this.RequestAttachments = new HashSet<RequestAttachment>();
            this.AssetsEventTrackings = new HashSet<AssetsEventTracking>();
        }
    
        public int Code { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string RequestRefCode { get; set; }
        public Nullable<int> RequestActionType { get; set; }
        public Nullable<int> ProcessType { get; set; }
        public Nullable<int> TMonth { get; set; }
        public Nullable<int> TYear { get; set; }
        public string Serial { get; set; }
        public Nullable<int> OrgChartRefCode { get; set; }
        public Nullable<int> ToLocationId { get; set; }
        public Nullable<int> EmpRefCode { get; set; }
        public string EmpName { get; set; }
        public string RequestNotes { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedAt { get; set; }
        public Nullable<int> TranferedRequestHeaderId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string AssetOrgOwnerRefCode { get; set; }
        public string AssetOrgOwnerName { get; set; }
        public Nullable<int> OrgEmpRefCode { get; set; }
        public string OrgEmpName { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestAttachment> RequestAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssetsEventTracking> AssetsEventTrackings { get; set; }
    }
}
