//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.DAL.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetsTransferOut
    {
        public int Id { get; set; }
        public Nullable<int> OrgRefCode { get; set; }
        public string Notes { get; set; }
        public string DeliveryAttach { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    }
}
