//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.DAL.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetsEventTracking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssetsEventTracking()
        {
            this.AssetsStores = new HashSet<AssetsStore>();
        }
    
        public int Code { get; set; }
        public Nullable<int> RequestHeaderCode { get; set; }
        public Nullable<long> AssetCode { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> actionId { get; set; }
        public Nullable<int> statusId { get; set; }
        public Nullable<int> ToLocationId { get; set; }
        public Nullable<int> EmpRefCode { get; set; }
        public string EmpName { get; set; }
        public string Notes { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedAt { get; set; }
        public Nullable<double> Qty { get; set; }
        public Nullable<double> MissedQty { get; set; }
        public string StoreRequestRefCode { get; set; }
        public Nullable<double> RequestItemPrice { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> ItemUsedStatus { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
    
        public virtual AssetsAvailabilityStatu AssetsAvailabilityStatu { get; set; }
        public virtual AssetsEventTrackingHeader AssetsEventTrackingHeader { get; set; }
        public virtual AssetsTrackingAction AssetsTrackingAction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssetsStore> AssetsStores { get; set; }
        public virtual D_ItemCard D_ItemCard { get; set; }
    }
}
