//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.DAL.Model.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AssetsEntitiesNew : DbContext
    {
        public AssetsEntitiesNew()
            : base("name=AssetsEntitiesNew")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AssetsAvailabilityStatu> AssetsAvailabilityStatus { get; set; }
        public virtual DbSet<AssetsItemUnit> AssetsItemUnits { get; set; }
        public virtual DbSet<AssetsTrackingAction> AssetsTrackingActions { get; set; }
        public virtual DbSet<D_AttachmentType> D_AttachmentType { get; set; }
        public virtual DbSet<D_Country> D_Country { get; set; }
        public virtual DbSet<D_EmployeeList> D_EmployeeList { get; set; }
        public virtual DbSet<D_EmployeeLocations> D_EmployeeLocations { get; set; }
        public virtual DbSet<D_InboundDepositeStatusType> D_InboundDepositeStatusType { get; set; }
        public virtual DbSet<D_InboundType> D_InboundType { get; set; }
        public virtual DbSet<D_ItemCard> D_ItemCard { get; set; }
        public virtual DbSet<D_ItemsCategory> D_ItemsCategory { get; set; }
        public virtual DbSet<D_ItemUsedStatus> D_ItemUsedStatus { get; set; }
        public virtual DbSet<D_JobTitle> D_JobTitle { get; set; }
        public virtual DbSet<D_Locations> D_Locations { get; set; }
        public virtual DbSet<D_LocationType> D_LocationType { get; set; }
        public virtual DbSet<D_QtyUnit> D_QtyUnit { get; set; }
        public virtual DbSet<D_VendorData> D_VendorData { get; set; }
        public virtual DbSet<Employee_tbl> Employee_tbl { get; set; }
        public virtual DbSet<Inbound> Inbounds { get; set; }
        public virtual DbSet<InboundAttachment> InboundAttachments { get; set; }
        public virtual DbSet<InboundNote> InboundNotes { get; set; }
        public virtual DbSet<InboundStatusTrack> InboundStatusTracks { get; set; }
        public virtual DbSet<InboundStoreEmployee> InboundStoreEmployees { get; set; }
        public virtual DbSet<Item_tbl> Item_tbl { get; set; }
        public virtual DbSet<RequestAttachment> RequestAttachments { get; set; }
        public virtual DbSet<Security_pr_admin> Security_pr_admin { get; set; }
        public virtual DbSet<Security_pr_AdminType> Security_pr_AdminType { get; set; }
        public virtual DbSet<Security_pr_MainSystem> Security_pr_MainSystem { get; set; }
        public virtual DbSet<Security_pr_ModuleThemes> Security_pr_ModuleThemes { get; set; }
        public virtual DbSet<Security_pr_Permission> Security_pr_Permission { get; set; }
        public virtual DbSet<Security_pr_SystemPages> Security_pr_SystemPages { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<view_AssetEventLog> view_AssetEventLog { get; set; }
        public virtual DbSet<view_AssetsInventory> view_AssetsInventory { get; set; }
        public virtual DbSet<view_AssetsList> view_AssetsList { get; set; }
        public virtual DbSet<view_CustodyList> view_CustodyList { get; set; }
        public virtual DbSet<view_CustodyListGrouped> view_CustodyListGrouped { get; set; }
        public virtual DbSet<view_inboubdItems> view_inboubdItems { get; set; }
        public virtual DbSet<View_InboundList> View_InboundList { get; set; }
        public virtual DbSet<view_Inventory> view_Inventory { get; set; }
        public virtual DbSet<view_ItemCategoryTree> view_ItemCategoryTree { get; set; }
        public virtual DbSet<viewTemp> viewTemps { get; set; }
        public virtual DbSet<Security_pr_adminPermittedLocations> Security_pr_adminPermittedLocations { get; set; }
        public virtual DbSet<AssetsEventTracking> AssetsEventTrackings { get; set; }
        public virtual DbSet<D_OutboundRefType> D_OutboundRefType { get; set; }
        public virtual DbSet<D_OutboundType> D_OutboundType { get; set; }
        public virtual DbSet<Outbound_Items> Outbound_Items { get; set; }
        public virtual DbSet<OutboundAttachment> OutboundAttachments { get; set; }
        public virtual DbSet<OutboundNote> OutboundNotes { get; set; }
        public virtual DbSet<View_OutboundItems> View_OutboundItems { get; set; }
        public virtual DbSet<Outbound> Outbounds { get; set; }
        public virtual DbSet<View_OutboundList> View_OutboundList { get; set; }
        public virtual DbSet<view_ItemCard> view_ItemCard { get; set; }
        public virtual DbSet<view_AssetsEventTrackingHeader> view_AssetsEventTrackingHeader { get; set; }
        public virtual DbSet<AssetsEventTrackingHeader> AssetsEventTrackingHeaders { get; set; }
        public virtual DbSet<AssetsTransferOut> AssetsTransferOuts { get; set; }
    
        [DbFunction("AssetsEntitiesNew", "getChildNodeParentList")]
        public virtual IQueryable<getChildNodeParentList_Result> getChildNodeParentList(Nullable<int> childNodeId)
        {
            var childNodeIdParameter = childNodeId.HasValue ?
                new ObjectParameter("ChildNodeId", childNodeId) :
                new ObjectParameter("ChildNodeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<getChildNodeParentList_Result>("[AssetsEntitiesNew].[getChildNodeParentList](@ChildNodeId)", childNodeIdParameter);
        }
    
        [DbFunction("AssetsEntitiesNew", "getNodeChildList")]
        public virtual IQueryable<getNodeChildList_Result> getNodeChildList(Nullable<int> parentNodeId)
        {
            var parentNodeIdParameter = parentNodeId.HasValue ?
                new ObjectParameter("ParentNodeId", parentNodeId) :
                new ObjectParameter("ParentNodeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<getNodeChildList_Result>("[AssetsEntitiesNew].[getNodeChildList](@ParentNodeId)", parentNodeIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Security_SP_getPermissionsCount(Nullable<int> jobid, Nullable<int> userID)
        {
            var jobidParameter = jobid.HasValue ?
                new ObjectParameter("jobid", jobid) :
                new ObjectParameter("jobid", typeof(int));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Security_SP_getPermissionsCount", jobidParameter, userIDParameter);
        }
    
        public virtual ObjectResult<Security_SP_PRM_getJobPage_Result> Security_SP_PRM_getJobPage(Nullable<int> jobid, string url)
        {
            var jobidParameter = jobid.HasValue ?
                new ObjectParameter("jobid", jobid) :
                new ObjectParameter("jobid", typeof(int));
    
            var urlParameter = url != null ?
                new ObjectParameter("url", url) :
                new ObjectParameter("url", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Security_SP_PRM_getJobPage_Result>("Security_SP_PRM_getJobPage", jobidParameter, urlParameter);
        }
    
        public virtual ObjectResult<Security_SP_PRM_getJobPermissions_Result> Security_SP_PRM_getJobPermissions(Nullable<int> jobid)
        {
            var jobidParameter = jobid.HasValue ?
                new ObjectParameter("jobid", jobid) :
                new ObjectParameter("jobid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Security_SP_PRM_getJobPermissions_Result>("Security_SP_PRM_getJobPermissions", jobidParameter);
        }
    
        public virtual ObjectResult<Security_SP_PRM_getSystemPermission_Result> Security_SP_PRM_getSystemPermission(Nullable<int> jobid, Nullable<int> userid)
        {
            var jobidParameter = jobid.HasValue ?
                new ObjectParameter("jobid", jobid) :
                new ObjectParameter("jobid", typeof(int));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Security_SP_PRM_getSystemPermission_Result>("Security_SP_PRM_getSystemPermission", jobidParameter, useridParameter);
        }
    
        public virtual ObjectResult<Security_SP_PRM_getUserPage_Result> Security_SP_PRM_getUserPage(Nullable<int> jobid, Nullable<int> empid, string url)
        {
            var jobidParameter = jobid.HasValue ?
                new ObjectParameter("jobid", jobid) :
                new ObjectParameter("jobid", typeof(int));
    
            var empidParameter = empid.HasValue ?
                new ObjectParameter("empid", empid) :
                new ObjectParameter("empid", typeof(int));
    
            var urlParameter = url != null ?
                new ObjectParameter("url", url) :
                new ObjectParameter("url", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Security_SP_PRM_getUserPage_Result>("Security_SP_PRM_getUserPage", jobidParameter, empidParameter, urlParameter);
        }
    
        public virtual ObjectResult<Security_SP_PRM_getuserPermissions_Result> Security_SP_PRM_getuserPermissions(Nullable<int> jobid, Nullable<int> userID)
        {
            var jobidParameter = jobid.HasValue ?
                new ObjectParameter("jobid", jobid) :
                new ObjectParameter("jobid", typeof(int));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Security_SP_PRM_getuserPermissions_Result>("Security_SP_PRM_getuserPermissions", jobidParameter, userIDParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual ObjectResult<sp_CategoryItemList_Result> sp_CategoryItemList(Nullable<int> nodeId)
        {
            var nodeIdParameter = nodeId.HasValue ?
                new ObjectParameter("NodeId", nodeId) :
                new ObjectParameter("NodeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_CategoryItemList_Result>("sp_CategoryItemList", nodeIdParameter);
        }
    
        public virtual int sp_clearEntityLocations(Nullable<int> entityId)
        {
            var entityIdParameter = entityId.HasValue ?
                new ObjectParameter("EntityId", entityId) :
                new ObjectParameter("EntityId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_clearEntityLocations", entityIdParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_ItemAutoComp_Result> sp_ItemAutoComp(string pre)
        {
            var preParameter = pre != null ?
                new ObjectParameter("pre", pre) :
                new ObjectParameter("pre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ItemAutoComp_Result>("sp_ItemAutoComp", preParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_setEntityLocations(Nullable<int> entityId, string locationIds)
        {
            var entityIdParameter = entityId.HasValue ?
                new ObjectParameter("EntityId", entityId) :
                new ObjectParameter("EntityId", typeof(int));
    
            var locationIdsParameter = locationIds != null ?
                new ObjectParameter("LocationIds", locationIds) :
                new ObjectParameter("LocationIds", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_setEntityLocations", entityIdParameter, locationIdsParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int sp_getEntityEmployeeList(Nullable<int> nodeId)
        {
            var nodeIdParameter = nodeId.HasValue ?
                new ObjectParameter("NodeId", nodeId) :
                new ObjectParameter("NodeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_getEntityEmployeeList", nodeIdParameter);
        }
    
        public virtual ObjectResult<GetAssetUnitsCostDetails_Result> GetAssetUnitsCostDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAssetUnitsCostDetails_Result>("GetAssetUnitsCostDetails");
        }
    
        public virtual ObjectResult<GetAssetUnitsCostCompare_Result> GetAssetUnitsCostCompare()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAssetUnitsCostCompare_Result>("GetAssetUnitsCostCompare");
        }
    
        public virtual ObjectResult<Get_Emp_Location_Result> Get_Emp_Location(Nullable<int> empId)
        {
            var empIdParameter = empId.HasValue ?
                new ObjectParameter("EmpId", empId) :
                new ObjectParameter("EmpId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Emp_Location_Result>("Get_Emp_Location", empIdParameter);
        }
    
        public virtual ObjectResult<sp_LocationTree_Result> sp_LocationTree(Nullable<int> startingNode)
        {
            var startingNodeParameter = startingNode.HasValue ?
                new ObjectParameter("StartingNode", startingNode) :
                new ObjectParameter("StartingNode", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LocationTree_Result>("sp_LocationTree", startingNodeParameter);
        }
    
        public virtual ObjectResult<sp_GetAllAssetsTypeCount_Result> sp_GetAllAssetsTypeCount()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAllAssetsTypeCount_Result>("sp_GetAllAssetsTypeCount");
        }
    
        public virtual ObjectResult<sp_GetAllEmployeesCount_Result> sp_GetAllEmployeesCount()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAllEmployeesCount_Result>("sp_GetAllEmployeesCount");
        }
    
        public virtual ObjectResult<sp_GetAllEmpsHaveAssetsCount_Result> sp_GetAllEmpsHaveAssetsCount()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAllEmpsHaveAssetsCount_Result>("sp_GetAllEmpsHaveAssetsCount");
        }
    
        public virtual ObjectResult<sp_GetAllEmpsHaveAssetsDetails_Result> sp_GetAllEmpsHaveAssetsDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAllEmpsHaveAssetsDetails_Result>("sp_GetAllEmpsHaveAssetsDetails");
        }
    }
}
