//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.DAL.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_EmployeeList
    {
        public int Code { get; set; }
        public Nullable<int> JobTitleId { get; set; }
        public Nullable<int> LocationRefCode { get; set; }
        public Nullable<int> EmpCode { get; set; }
        public string EmpName { get; set; }
        public string CivilId { get; set; }
        public string Phone { get; set; }
        public string Phone1 { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual D_JobTitle D_JobTitle { get; set; }
    }
}
