//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.DAL.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_ItemCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public D_ItemCard()
        {
            this.Outbound_Items = new HashSet<Outbound_Items>();
            this.AssetsEventTrackings = new HashSet<AssetsEventTracking>();
            this.AssetsItemUnits = new HashSet<AssetsItemUnit>();
        }
    
        public long Code { get; set; }
        public string ItemRefCode { get; set; }
        public string ItemBarCode { get; set; }
        public string ItemRFIDCode { get; set; }
        public string ItemFinanceCode { get; set; }
        public string ItemQrCode { get; set; }
        public string ItemNameEn { get; set; }
        public string ItemNameAr { get; set; }
        public string ItemDescEn { get; set; }
        public string ItemDescAr { get; set; }
        public Nullable<int> ItemCategoryId { get; set; }
        public Nullable<double> ItemBasePrice { get; set; }
        public Nullable<int> QUnitCode { get; set; }
        public Nullable<int> MinQty { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedAt { get; set; }
        public string ItemImage { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<double> ScrapPeriod { get; set; }
        public Nullable<double> ScrapAmount { get; set; }
        public Nullable<double> ItemMasterPrice { get; set; }
        public Nullable<int> REFID { get; set; }
        public Nullable<bool> CountableFlag { get; set; }
        public Nullable<bool> OrganizedFlag { get; set; }
        public string PictureName { get; set; }
        public Nullable<int> Item_StateId { get; set; }
        public Nullable<int> OutFlag { get; set; }
        public Nullable<int> TransFlag { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual D_ItemsCategory D_ItemsCategory { get; set; }
        public virtual D_QtyUnit D_QtyUnit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Outbound_Items> Outbound_Items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssetsEventTracking> AssetsEventTrackings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssetsItemUnit> AssetsItemUnits { get; set; }
    }
}
