//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.DAL.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_Locations
    {
        public int Code { get; set; }
        public Nullable<int> LocationType { get; set; }
        public string LocationNameEn { get; set; }
        public string LocationNameAr { get; set; }
        public Nullable<int> LocationParentId { get; set; }
        public Nullable<int> OrgChartRefCode { get; set; }
        public Nullable<int> EmpInCharge { get; set; }
        public Nullable<bool> IsScrap { get; set; }
        public string LocationRefCode { get; set; }
        public Nullable<int> MigrationRef { get; set; }
        public Nullable<int> MigrationRef1 { get; set; }
        public Nullable<bool> AllowInbound { get; set; }
        public string City { get; set; }
    
        public virtual D_LocationType D_LocationType { get; set; }
    }
}
