//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.DAL.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_VendorData
    {
        public int Code { get; set; }
        public string VendorNameEn { get; set; }
        public string VendorNameAr { get; set; }
        public string RefCode { get; set; }
        public string Phone { get; set; }
        public string fax { get; set; }
        public string Email { get; set; }
        public Nullable<int> Country { get; set; }
        public string ContactPerson { get; set; }
        public string ContactpersonPhone { get; set; }
        public string AddressDetails { get; set; }
        public string Notes { get; set; }
        public string logo { get; set; }
    
        public virtual D_Country D_Country { get; set; }
    }
}
