//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.DAL.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class InboundAttachment
    {
        public long Code { get; set; }
        public Nullable<int> InboundCode { get; set; }
        public string FileName { get; set; }
        public string Notes { get; set; }
        public Nullable<int> AttachmentTypCode { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual D_AttachmentType D_AttachmentType { get; set; }
        public virtual Inbound Inbound { get; set; }
    }
}
