//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.DAL.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inbound
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inbound()
        {
            this.AssetsItemUnits = new HashSet<AssetsItemUnits>();
            this.InboundAttachments = new HashSet<InboundAttachments>();
            this.InboundNotes = new HashSet<InboundNotes>();
            this.InboundStatusTrack = new HashSet<InboundStatusTrack>();
            this.InboundStoreEmployee = new HashSet<InboundStoreEmployee>();
        }
    
        public int Code { get; set; }
        public string Serial { get; set; }
        public Nullable<int> InboundTypeCode { get; set; }
        public string InBoundRefCode { get; set; }
        public Nullable<int> TMonth { get; set; }
        public Nullable<int> TYear { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<int> TargetLocationCode { get; set; }
        public Nullable<int> FromVendorCode { get; set; }
        public Nullable<int> OwnerLocationCode { get; set; }
        public string RefNo { get; set; }
        public Nullable<System.DateTime> RefDate { get; set; }
        public string Notes { get; set; }
        public string DeliveryOrderNo { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string DepositeNotes { get; set; }
        public Nullable<int> OutBoundRefCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssetsItemUnits> AssetsItemUnits { get; set; }
        public virtual D_InboundType D_InboundType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InboundAttachments> InboundAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InboundNotes> InboundNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InboundStatusTrack> InboundStatusTrack { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InboundStoreEmployee> InboundStoreEmployee { get; set; }
    }
}
