//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.DAL.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_tbl
    {
        public long Item_Id { get; set; }
        public string Item_Name { get; set; }
        public string Item_NameEn { get; set; }
        public Nullable<int> Unit_Id { get; set; }
        public Nullable<int> CatSub_Id { get; set; }
        public string Item_State { get; set; }
        public string Item_Dec { get; set; }
        public Nullable<int> Item_Count { get; set; }
        public Nullable<double> Item_Price { get; set; }
        public Nullable<double> Item_Discount { get; set; }
        public string Item_Remarks { get; set; }
        public Nullable<int> User_Id { get; set; }
        public Nullable<int> Item_Active { get; set; }
        public string Item_BarCode { get; set; }
        public string Item_RFID { get; set; }
        public Nullable<System.DateTime> Item_LastUpdate { get; set; }
        public Nullable<long> Room_Id { get; set; }
        public Nullable<int> Emp_Id { get; set; }
        public Nullable<int> Depart_Id { get; set; }
        public Nullable<System.DateTime> Item_AssDate { get; set; }
        public Nullable<int> item_lowqty { get; set; }
        public Nullable<System.DateTime> Item_Expire { get; set; }
        public Nullable<int> Item_dayhint { get; set; }
        public string Item_FinCode { get; set; }
        public Nullable<bool> Item_stopAlram { get; set; }
        public string PurchaseOrder { get; set; }
        public string InvoiceNo { get; set; }
        public string Model { get; set; }
        public string Origin { get; set; }
        public string AssetCardNo { get; set; }
        public Nullable<System.DateTime> OperationDate { get; set; }
        public string PurchasingPower { get; set; }
        public string Category { get; set; }
        public Nullable<bool> CountableFlag { get; set; }
        public Nullable<bool> OrganizedFlag { get; set; }
        public string PictureName { get; set; }
        public Nullable<int> Item_StateId { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> OutFlag { get; set; }
        public Nullable<int> TransFlag { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
