//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.DAL.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Outbound_Items
    {
        public long Code { get; set; }
        public Nullable<long> OutboundCode { get; set; }
        public Nullable<int> QtyUnitCode { get; set; }
        public Nullable<double> Qty { get; set; }
        public Nullable<double> EstimatedAmount { get; set; }
        public Nullable<System.DateTime> OutTransDate { get; set; }
        public Nullable<int> ItemCode { get; set; }
        public string Notes { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedAt { get; set; }
        public Nullable<int> UnitStatus { get; set; }
    
        public virtual D_ItemCard D_ItemCard { get; set; }
        public virtual D_ItemUsedStatus D_ItemUsedStatus { get; set; }
        public virtual Outbound Outbound { get; set; }
    }
}
