//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.DAL.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Security_pr_admin
    {
        public int id { get; set; }
        public string name { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<int> AdminType { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string mobile { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public string AdminPhoto { get; set; }
        public Nullable<bool> isOperation { get; set; }
        public string AccessCompnayGroup { get; set; }
    
        public virtual Security_pr_AdminType Security_pr_AdminType { get; set; }
    }
}
