//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.DAL.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Security_pr_adminPermittedOrgUnits
    {
        public int Code { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> OrgChartRefCode { get; set; }
    
        public virtual Security_pr_admin Security_pr_admin { get; set; }
    }
}
