//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.DAL.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemLog
    {
        public int LogId { get; set; }
        public string UserId { get; set; }
        public string UserName { get; set; }
        public string TableName { get; set; }
        public string RecordId { get; set; }
        public string Action { get; set; }
        public string Page { get; set; }
        public string IPAddress { get; set; }
        public string AdditionalInfo { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
    }
}
