//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.DAL.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_Inventory
    {
        public string groupname { get; set; }
        public int Code { get; set; }
        public string CategoryTitleAr { get; set; }
        public string CategoryTitleEn { get; set; }
        public string ItemFinanceCode { get; set; }
        public string ItemNameEn { get; set; }
        public string ItemNameAr { get; set; }
        public string Serial { get; set; }
        public Nullable<int> TMonth { get; set; }
        public Nullable<int> TYear { get; set; }
        public Nullable<int> InboundCode { get; set; }
        public Nullable<int> ItemCode { get; set; }
        public Nullable<double> ReceivedQty { get; set; }
        public Nullable<double> EstimatedUnitCost { get; set; }
        public Nullable<int> ToLocationId { get; set; }
        public string LocationNameEn { get; set; }
        public string LocationNameAr { get; set; }
        public Nullable<int> OrgChartRefCode { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
    }
}
