//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.DAL.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_OutboundItems
    {
        public long Code { get; set; }
        public Nullable<long> OutboundCode { get; set; }
        public Nullable<int> QtyUnitCode { get; set; }
        public Nullable<double> Qty { get; set; }
        public Nullable<double> EstimatedAmount { get; set; }
        public Nullable<System.DateTime> OutTransDate { get; set; }
        public Nullable<int> ItemCode { get; set; }
        public Nullable<int> UnitStatus { get; set; }
        public string Notes { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedAt { get; set; }
        public string unitCodeTitleAr { get; set; }
        public string unitCodeTitleEn { get; set; }
        public string ItemRefCode { get; set; }
        public string ItemBarCode { get; set; }
        public string ItemRFIDCode { get; set; }
        public string ItemFinanceCode { get; set; }
        public string ItemQrCode { get; set; }
        public string ItemNameEn { get; set; }
        public string ItemNameAr { get; set; }
        public string ItemDescEn { get; set; }
        public string ItemDescAr { get; set; }
        public string ItemCategoryTitleAr { get; set; }
        public string ItemCategoryTitleEn { get; set; }
        public Nullable<double> ItemBasePrice { get; set; }
        public string StatusNameAr { get; set; }
        public string StatusNameEn { get; set; }
        public string OutboundItemNotes { get; set; }
    }
}
