//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.DAL.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_OutboundList
    {
        public long Code { get; set; }
        public string Serial { get; set; }
        public Nullable<int> TMonth { get; set; }
        public Nullable<int> TYear { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<int> TypeCode { get; set; }
        public Nullable<int> WithdrawTypeCode { get; set; }
        public Nullable<int> RefTypeCode { get; set; }
        public string RefNo { get; set; }
        public Nullable<System.DateTime> RefDate { get; set; }
        public string Notes { get; set; }
        public Nullable<double> ServiceCost { get; set; }
        public string ReceiteNo { get; set; }
        public Nullable<System.DateTime> ReceiteDate { get; set; }
        public Nullable<int> FromLocationCode { get; set; }
        public Nullable<int> ToLocationCode { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedAt { get; set; }
        public string FromLocationNameEn { get; set; }
        public string FromLocationNameAr { get; set; }
        public string ToLocationNameEn { get; set; }
        public string ToLocationNameAr { get; set; }
        public string RefTypeTitleAr { get; set; }
        public string RefTypeTitleEn { get; set; }
        public string OutboundTypeTitleAr { get; set; }
        public string OutboundTypeTitleEn { get; set; }
    }
}
