//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.DAL.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_InboundList
    {
        public int Code { get; set; }
        public string Serial { get; set; }
        public string InBoundRefCode { get; set; }
        public Nullable<int> TMonth { get; set; }
        public Nullable<int> TYear { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<int> InboundTypeCode { get; set; }
        public Nullable<int> TargetLocationCode { get; set; }
        public Nullable<int> FromVendorCode { get; set; }
        public Nullable<int> OwnerLocationCode { get; set; }
        public string RefNo { get; set; }
        public Nullable<System.DateTime> RefDate { get; set; }
        public string Notes { get; set; }
        public string DeliveryOrderNo { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string DepositeNotes { get; set; }
        public string TypeTitleAr { get; set; }
        public string TypeTitleEn { get; set; }
        public string InboundLastStatus { get; set; }
        public string VendorNameEn { get; set; }
        public string VendorNameAr { get; set; }
        public string LocationNameEn { get; set; }
        public string LocationNameAr { get; set; }
        public Nullable<int> InboundLastStatusCode { get; set; }
    }
}
