//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.DAL.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_AssetsInventory
    {
        public long PKey { get; set; }
        public string groupname { get; set; }
        public int Code { get; set; }
        public string CategoryTitleAr { get; set; }
        public string CategoryTitleEn { get; set; }
        public string ItemFinanceCode { get; set; }
        public string ItemNameEn { get; set; }
        public string ItemNameAr { get; set; }
        public string Serial { get; set; }
        public Nullable<int> TMonth { get; set; }
        public Nullable<int> TYear { get; set; }
        public Nullable<int> InboundCode { get; set; }
        public Nullable<int> ItemCode { get; set; }
        public Nullable<double> ReceivedQty { get; set; }
        public Nullable<double> EstimatedUnitCost { get; set; }
        public Nullable<int> ToLocationId { get; set; }
        public string LocationNameEn { get; set; }
        public string LocationNameAr { get; set; }
        public Nullable<int> OrgChartRefCode { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public int ORG_NO { get; set; }
        public string ORG_NAME { get; set; }
        public int AMANA_NO { get; set; }
        public string AMANA_NAME { get; set; }
        public int DEPT_NO { get; set; }
        public string DEPT_NAME { get; set; }
        public int DIV_NO { get; set; }
        public string DIV_NAME { get; set; }
        public int SEC_NO { get; set; }
        public string SEC_NAME { get; set; }
        public int SUB_SEC_NO { get; set; }
        public string SUB_SEC_NAME { get; set; }
        public string JOB_NAME { get; set; }
    }
}
