//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.DAL.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_LocationTree
    {
        public long PKey { get; set; }
        public Nullable<int> code { get; set; }
        public Nullable<int> LocationParentId { get; set; }
        public Nullable<int> LEVEL { get; set; }
        public string LocationNameAr { get; set; }
        public Nullable<int> LocationType { get; set; }
        public string path { get; set; }
    }
}
